## Latihan 4 (operasi matriks)

In [1]:
import numpy as np

In [6]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

print(A)
print(B)

[[1 2]
 [7 8]]
[[3 5]
 [1 6]]


Hitunglah:

* 2*A
* 2+A
* A+B
* A-B
* determinan A
* invers dari B, simpan jadi matriks D
* transpose D
*nilai eigen dan vektor eigen dari A dan B

In [32]:
print("2*A:\n", 2*A)

2*A:
 [[ 2  4]
 [14 16]]


In [33]:
print("2+A:\n", 2+A)

2+A:
 [[ 3  4]
 [ 9 10]]


In [18]:
print("A+B=\n", A+B)

A+B=
 [[ 4  7]
 [ 8 14]]


In [19]:
print("A-B=\n", A-B)

A-B=
 [[-2 -3]
 [ 6  2]]


In [15]:
print("Determinan A:\n", np.linalg.det(A))

Determinan A:
 -6.0


In [13]:
d = np.linalg.inv(B)
print("D:\n", d)

D:
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [23]:
transD = d.transpose()
print("Transpose D:\n", transD)

Transpose D:
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [30]:
print("Nilai eigen dan vektor eigen matriks A:\n", np.linalg.eig(A))

Nilai eigen dan vektor eigen matriks A:
 (array([-0.62347538,  9.62347538]), array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]]))


In [29]:
print("Nilai eigen dan vektor eigen matriks B:\n", np.linalg.eig(B))

Nilai eigen dan vektor eigen matriks B:
 (array([1.8074176, 7.1925824]), array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]]))
